// Code generated by gonstructor --output=events.gen.go --type=NewMessageEvent --type=MessageSentEvent --type=MessageBlockedEvent --type=NewChatEvent --type=NewManagerMessageEvent --type=ChatClosedEvent; DO NOT EDIT.

package eventstream

import (
	"time"

	"github.com/karasunokami/chat-service/internal/types"
)

func NewNewMessageEvent(
	eventID types.EventID,
	requestID types.RequestID,
	chatID types.ChatID,
	messageID types.MessageID,
	createdAt time.Time,
	messageBody string,
	authorID types.UserID,
	isService bool,
) *NewMessageEvent {
	return &NewMessageEvent{
		EventID:     eventID,
		RequestID:   requestID,
		ChatID:      chatID,
		MessageID:   messageID,
		CreatedAt:   createdAt,
		MessageBody: messageBody,
		AuthorID:    authorID,
		IsService:   isService,
	}
}

func NewMessageSentEvent(
	eventID types.EventID,
	requestID types.RequestID,
	messageID types.MessageID,
) *MessageSentEvent {
	return &MessageSentEvent{
		EventID:   eventID,
		RequestID: requestID,
		MessageID: messageID,
	}
}

func NewMessageBlockedEvent(
	eventID types.EventID,
	requestID types.RequestID,
	messageID types.MessageID,
) *MessageBlockedEvent {
	return &MessageBlockedEvent{
		EventID:   eventID,
		RequestID: requestID,
		MessageID: messageID,
	}
}

func NewNewChatEvent(
	canTakeMoreProblems bool,
	eventID types.EventID,
	requestID types.RequestID,
	chatID types.ChatID,
	clientID types.UserID,
) *NewChatEvent {
	return &NewChatEvent{
		CanTakeMoreProblems: canTakeMoreProblems,
		EventID:             eventID,
		RequestID:           requestID,
		ChatID:              chatID,
		ClientID:            clientID,
	}
}

func NewNewManagerMessageEvent(
	eventID types.EventID,
	requestID types.RequestID,
	chatID types.ChatID,
	messageID types.MessageID,
	createdAt time.Time,
	messageBody string,
	authorID types.UserID,
) *NewManagerMessageEvent {
	return &NewManagerMessageEvent{
		EventID:     eventID,
		RequestID:   requestID,
		ChatID:      chatID,
		MessageID:   messageID,
		CreatedAt:   createdAt,
		MessageBody: messageBody,
		AuthorID:    authorID,
	}
}

func NewChatClosedEvent(
	canTakeMoreProblems bool,
	chatID types.ChatID,
	eventID types.EventID,
	requestID types.RequestID,
) *ChatClosedEvent {
	return &ChatClosedEvent{
		CanTakeMoreProblems: canTakeMoreProblems,
		ChatID:              chatID,
		EventID:             eventID,
		RequestID:           requestID,
	}
}
