// Code generated by ent, DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/karasunokami/chat-service/internal/store/failedjob"
	"github.com/karasunokami/chat-service/internal/types"
)

// FailedJobCreate is the builder for creating a FailedJob entity.
type FailedJobCreate struct {
	config
	mutation *FailedJobMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (fjc *FailedJobCreate) SetName(s string) *FailedJobCreate {
	fjc.mutation.SetName(s)
	return fjc
}

// SetPayload sets the "payload" field.
func (fjc *FailedJobCreate) SetPayload(s string) *FailedJobCreate {
	fjc.mutation.SetPayload(s)
	return fjc
}

// SetReason sets the "reason" field.
func (fjc *FailedJobCreate) SetReason(s string) *FailedJobCreate {
	fjc.mutation.SetReason(s)
	return fjc
}

// SetCreatedAt sets the "created_at" field.
func (fjc *FailedJobCreate) SetCreatedAt(t time.Time) *FailedJobCreate {
	fjc.mutation.SetCreatedAt(t)
	return fjc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fjc *FailedJobCreate) SetNillableCreatedAt(t *time.Time) *FailedJobCreate {
	if t != nil {
		fjc.SetCreatedAt(*t)
	}
	return fjc
}

// SetID sets the "id" field.
func (fjc *FailedJobCreate) SetID(tji types.FailedJobID) *FailedJobCreate {
	fjc.mutation.SetID(tji)
	return fjc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (fjc *FailedJobCreate) SetNillableID(tji *types.FailedJobID) *FailedJobCreate {
	if tji != nil {
		fjc.SetID(*tji)
	}
	return fjc
}

// Mutation returns the FailedJobMutation object of the builder.
func (fjc *FailedJobCreate) Mutation() *FailedJobMutation {
	return fjc.mutation
}

// Save creates the FailedJob in the database.
func (fjc *FailedJobCreate) Save(ctx context.Context) (*FailedJob, error) {
	fjc.defaults()
	return withHooks[*FailedJob, FailedJobMutation](ctx, fjc.sqlSave, fjc.mutation, fjc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fjc *FailedJobCreate) SaveX(ctx context.Context) *FailedJob {
	v, err := fjc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fjc *FailedJobCreate) Exec(ctx context.Context) error {
	_, err := fjc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fjc *FailedJobCreate) ExecX(ctx context.Context) {
	if err := fjc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fjc *FailedJobCreate) defaults() {
	if _, ok := fjc.mutation.CreatedAt(); !ok {
		v := failedjob.DefaultCreatedAt
		fjc.mutation.SetCreatedAt(v)
	}
	if _, ok := fjc.mutation.ID(); !ok {
		v := failedjob.DefaultID()
		fjc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fjc *FailedJobCreate) check() error {
	if _, ok := fjc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`store: missing required field "FailedJob.name"`)}
	}
	if v, ok := fjc.mutation.Name(); ok {
		if err := failedjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`store: validator failed for field "FailedJob.name": %w`, err)}
		}
	}
	if _, ok := fjc.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`store: missing required field "FailedJob.payload"`)}
	}
	if v, ok := fjc.mutation.Payload(); ok {
		if err := failedjob.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`store: validator failed for field "FailedJob.payload": %w`, err)}
		}
	}
	if _, ok := fjc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`store: missing required field "FailedJob.reason"`)}
	}
	if v, ok := fjc.mutation.Reason(); ok {
		if err := failedjob.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`store: validator failed for field "FailedJob.reason": %w`, err)}
		}
	}
	if _, ok := fjc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`store: missing required field "FailedJob.created_at"`)}
	}
	if v, ok := fjc.mutation.ID(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`store: validator failed for field "FailedJob.id": %w`, err)}
		}
	}
	return nil
}

func (fjc *FailedJobCreate) sqlSave(ctx context.Context) (*FailedJob, error) {
	if err := fjc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fjc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fjc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*types.FailedJobID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	fjc.mutation.id = &_node.ID
	fjc.mutation.done = true
	return _node, nil
}

func (fjc *FailedJobCreate) createSpec() (*FailedJob, *sqlgraph.CreateSpec) {
	var (
		_node = &FailedJob{config: fjc.config}
		_spec = sqlgraph.NewCreateSpec(failedjob.Table, sqlgraph.NewFieldSpec(failedjob.FieldID, field.TypeUUID))
	)
	if id, ok := fjc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := fjc.mutation.Name(); ok {
		_spec.SetField(failedjob.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := fjc.mutation.Payload(); ok {
		_spec.SetField(failedjob.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := fjc.mutation.Reason(); ok {
		_spec.SetField(failedjob.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := fjc.mutation.CreatedAt(); ok {
		_spec.SetField(failedjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// FailedJobCreateBulk is the builder for creating many FailedJob entities in bulk.
type FailedJobCreateBulk struct {
	config
	builders []*FailedJobCreate
}

// Save creates the FailedJob entities in the database.
func (fjcb *FailedJobCreateBulk) Save(ctx context.Context) ([]*FailedJob, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fjcb.builders))
	nodes := make([]*FailedJob, len(fjcb.builders))
	mutators := make([]Mutator, len(fjcb.builders))
	for i := range fjcb.builders {
		func(i int, root context.Context) {
			builder := fjcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FailedJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fjcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fjcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fjcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fjcb *FailedJobCreateBulk) SaveX(ctx context.Context) []*FailedJob {
	v, err := fjcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fjcb *FailedJobCreateBulk) Exec(ctx context.Context) error {
	_, err := fjcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fjcb *FailedJobCreateBulk) ExecX(ctx context.Context) {
	if err := fjcb.Exec(ctx); err != nil {
		panic(err)
	}
}
