[global]
env = "dev"

# Logger

[log]
level = "info"

# Servers

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
sec_ws_protocol = "chat-service-protocol"

[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"

[servers.manager]
addr = ":8081"
allow_origins = ["http://localhost:3011", "http://localhost:3001"]
sec_ws_protocol = "chat-service-protocol"

[servers.manager.required_access]
resource = "chat-ui-manager"
role = "support-chat-manager"

# Deps

[sentry]
dsn = "http://8386679e9758470f9bb586ce1132dd4e@localhost:9000/2"

# Deps clients

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "63BYwNafWBXbH0tRCdIhQ5ZAj91uj0bd"
debug_mode = false
[clients.psql]
address = "127.0.0.1:5432"
username = "chat-service"
password = "chat-service"
database = "chat-service"
debug_mode = false

# Services

[services]
[services.msg_producer]
brokers = ["localhost:9092"]
topic = "chat.messages"
batch_size = 1
encrypt_key = "51655468576D5A7134743777397A2443" # Leave it blank to disable encryption.

[services.outbox]
workers = 10
idle_time = "1s"
reserve_for = "5m"

[services.manager_load]
max_problems_at_same_time = 10

[services.afc_verdicts_processor]
brokers = ["localhost:9092"]
consumers_count = 4
consumers_group_name = "group"
verdicts_topic_name = "afc.msg-verdicts"
verdicts_dql_topic_name = "afc.msg-verdicts.dlq"
verdicts_signing_public_key = """
-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgHfj1jei7ySAjFFqvwsabfSXpAH7
iMQKYcYSLuXULYKTX0crg8ZaZs0P9HQkl2Y24snMlmQWeT43DPfAt49MKcvR6pcZ
JaBqrPJq5sXcjLWJ5n5wkKzEvGn3a8W6EygIJKJiaYLUS9qOQz2MBx4q3y2s4aE6
Qer9hpNqGfW7uBmNAgMBAAE=
-----END PUBLIC KEY-----
"""

[services.manager_scheduler]
period = "1s"
