[global]
env = "dev"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]

[sentry]
dsn = "http://8386679e9758470f9bb586ce1132dd4e@localhost:9000/2"
