// Package managerevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.1-0.20230606151810-f5363b0149ef DO NOT EDIT.
package managerevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/karasunokami/chat-service/internal/types"
)

// DefaultEvent defines model for DefaultEvent.
type DefaultEvent struct {
	EventId   types.EventID   `json:"eventId"`
	EventType string          `json:"eventType"`
	RequestId types.RequestID `json:"requestId"`
}

// Event defines model for Event.
type Event struct {
	EventType string `json:"eventType"`
	union     json.RawMessage
}

// NewChatEvent defines model for NewChatEvent.
type NewChatEvent struct {
	CanTakeMoreProblems bool            `json:"canTakeMoreProblems"`
	ChatId              types.ChatID    `json:"chatId"`
	ClientId            types.UserID    `json:"clientId"`
	EventId             types.EventID   `json:"eventId"`
	EventType           string          `json:"eventType"`
	RequestId           types.RequestID `json:"requestId"`
}

// AsNewChatEvent returns the union data inside the Event as a NewChatEvent
func (t Event) AsNewChatEvent() (NewChatEvent, error) {
	var body NewChatEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewChatEvent overwrites any union data inside the Event as the provided NewChatEvent
func (t *Event) FromNewChatEvent(v NewChatEvent) error {
	t.EventType = "NewChatEvent"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewChatEvent performs a merge with any union data inside the Event, using the provided NewChatEvent
func (t *Event) MergeNewChatEvent(v NewChatEvent) error {
	t.EventType = "NewChatEvent"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"eventType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "NewChatEvent":
		return t.AsNewChatEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["eventType"], err = json.Marshal(t.EventType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'eventType': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["eventType"]; found {
		err = json.Unmarshal(raw, &t.EventType)
		if err != nil {
			return fmt.Errorf("error reading 'eventType': %w", err)
		}
	}

	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7yUwU4bMRCGX2U1rdSLE4f2gnxsqSoOQFXoCXFwNpNdE6/H9cwmRVHevbKzwEKhqqho",
	"LnHWOzP/zP9NtlBTFylgEAazBa5b7Gw5HuHS9l4+rzFI/h0TRUzisNxifny8yMclpc4KGOh7twAFchMR",
	"DLAkFxpQ8HPS0GR4mL94WnIeH43vJq6LlPaFrLRgoHHS9vNpTZ1e2WS5D7SyndN1a2XCmNauRu2CYArW",
	"65IYdju1V3ZRym0fadkpSPijR36x8m9D+KtoH+S5hAswl3cjHoset3d1J5jm11hLbu/OrYXjOrnOBSuU",
	"RvbdnNouh9yn2SmggGdLMJdbeJtwCQbe6Hss9MCEPsXNp9YOQOyu1FNEPDP3pzp7tocHdcwWrPd/oe4B",
	"rjv1mNfahgu7whNK+DXR3GPHI51zIo825OrZopfSkWW/Fta1d/+wcd8Z03+BdhjfSK96cva/G39Vcrmw",
	"pGKME59vP9qwqs77mLVWeb7ViQ22wVQVpxkUrDGxowAG1geF5ojBRgcGPkwPpjNQpcFit2bp5/nQ4H5L",
	"MG9JlH34sVQ9I1dLSlWDAZMVF5qq0MrT6kxaTBvHWDmpFoQc3skUSr38JoVsDnxBOc9F8lg4UuA9f+9n",
	"s4IhBbnFOkbv6hKorzkLuP37zac/oT4wPnwUZG8wcVmRhx0d4Ro9xQ6DVPu3QEGfPBjYsNHaU219Syzm",
	"cHZ4oDecbfgVAAD//5yNy2gUBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
