openapi: 3.1.0
info:
  title: Bank Support Chat Client Events
  version: v1

servers:
  - url: ws://localhost:8080/ws
    description: Development server

paths:
  /stub:
    get:
      description: It uses for generating events. Otherwise it doesn't.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'

components:

  schemas:

    Event:
      required: [ eventId, messageId, requestId, eventType ]
      oneOf:
        - $ref: "#/components/schemas/NewMessageEvent"
        - $ref: "#/components/schemas/MessageSentEvent"
      discriminator:
        propertyName: eventType

    NewMessageEvent:
      required: [ eventId, messageId, requestId, eventType ]
      properties:
        authorId:
          type: string
          format: uuid
          x-go-type: types.UserID
          x-go-type-import:
            path: "github.com/karasunokami/chat-service/internal/types"
        body:
          type: string
        createdAt:
          type: string
          format: "date-time"
        eventId:
          type: string
          format: uuid
          x-go-type: types.EventID
          x-go-type-import:
            path: "github.com/karasunokami/chat-service/internal/types"
        eventType:
          type: string
        isService:
          type: boolean
        messageId:
          type: string
          format: uuid
          x-go-type: types.MessageID
          x-go-type-import:
            path: "github.com/karasunokami/chat-service/internal/types"
        requestId:
          type: string
          format: uuid
          x-go-type: types.RequestID
          x-go-type-import:
            path: "github.com/karasunokami/chat-service/internal/types"

    MessageSentEvent:
      required: [ eventId, messageId, requestId, eventType ]
      properties:
        eventType:
          type: string

        requestId:
          type: string
          format: uuid
          x-go-type: types.RequestID
          x-go-type-import:
            path: "github.com/karasunokami/chat-service/internal/types"

        eventId:
          type: string
          format: uuid
          x-go-type: types.EventID
          x-go-type-import:
            path: "github.com/karasunokami/chat-service/internal/types"

        messageId:
          type: string
          format: uuid
          x-go-type: types.MessageID
          x-go-type-import:
            path: "github.com/karasunokami/chat-service/internal/types"

# FIXME: Не забудь добавить новый контракт в debug server и Swagger UI.
